### A sample Gemfile
source 'https://rubygems.org'
### gem 'rails'
gem 'sinatra'
gem 'activerecord', '~> 6.1'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all' #=> Helps to load dependencies
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'rack-flash3'
gem 'sinatra-flash'